language: groovy
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
script: "./travis-build.sh"
env:
  global:
  - GIT_NAME="Zachary Klein"
  - GIT_EMAIL="kleinz@ociweb.com"
  - secure: ZSR28tPJgKHx5dbiYiIo2uS+642ufsHfyrL/sA8GFrpI4z8/U5oIfDi1wmhBQLEH4GWYwTd4OfczyDpYql7ezsruh6GYpiflct0qVjHlhlXTIVLcfcu/Ecvvg7m30VqdI/qyw1CdA5ptTmEFDW05TiWi9nzrTn32PnL+qXHCeKiShRqFmJcwsLjso9qY2ofUm382U860Y20mgLL6eRhdWaS+GADripOiJtrzZ+7tuqC3bZ3Q9u+P4NXsUy+X5ye+gxAyv8xa4IHWPcvHMX8yCOKTxfFpfUshSVoaqDW0sOJnnpAMXARYo7VmWmyYbodIDPULfuFbmZMfqD1dpkn0JBxfG5zIe4ngsopK5K61u677pwj9ZnavgM3dajQTvdi5thho6thedXSaZgcXpdNr9x8lE9HUgGzKGWitgKVT/NoyPr7zTrolG4q0FUAINY2DlcHDjdAKdqajbsyf+pyR9Pzj0s8qdoYxnebBKRDgXMMEWL++X2vB69+86IxbIM3Ta/4p/0joOSMEn/E0TZdrKN9/6X9oDGuSSRMDkM/wJAAEx+SV+p7DtyVWSeEjqsm5SmES8nxIJKM6IAExpS/wPGoNxS2BGK/JIf2B1y1rf0hvWEu7cT7oBRPRZQqgWN3dsSZ9XX+aPsbhFBCuz93qZr4b9bY014UMWhJHqyTUzLU=
  - secure: ZXFAaC0aHFs6ulu41IGREU0BTomTQC/R+IFLloBiEZZRe0uIy46MxB2wErn7cZlHasuzde26SSaZlOAabCQ5JECCN/whvzxIWXbjo0mTGQAcr9Zyy3t2aNsMZ9DG+qXijcq2ZeZiKZlDDjzJ7i0WzWNQVtpFlmOrYuZJg9tFxlN2P3U7kkxW3NgZS8n3CHHw5AZ10L1yyQI44HhapSbDGJs85pzlwQeywyXgPklFswkaNYOgKZtsew/Vi532jO1GqVZoOeUgCrUT3GTWM4geECPQDlZAi/+RzHfHsVF/ZAKTfLocSxlJDN9YFlPJ72rjSeTo3rCNgMFpIzRegNtaw8ncErqkDddIFCsWIBNwyNd/dshNwWYNOcXnty91BUBmLeAiZncKi3RPLrDMIutqy55TbKSo6vTDekYQ4/ZjF6/zvII5DWRMB2hWbqTL94OKYLkBqoJPwagoJ48oFnzpEe2qZ2dvy+58Bol6/YGwNNJxBs7Q71ZYzrrbg1vPLVrvmTWJrxBY5QGplimwM4Fx3ZN7TlAgejhRMFXJt0p28ujTveQ7k8fBe7OL8vYIUVQaruT8pcwPb2cvKE9zS55coq6w4vLqbdTGgqIC2jffKlfTuHmNPJH77vJawy8qNc+yGpUr2Yi10pElZIIY2EAKWub4XF9viXoDhtvZ+68ld0Y=
